
Name: Pull Request

on: [pull_request]

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-lastest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Cache node_modules  
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ HashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install 


  unusedexports:
    name: Find unused exports (dead code)
    runs-on: ubuntu-lastest
    needs: install
    steps: 
      - name: Checkout
        uses: actions/checkout@v3 

      - name: Restore node_modules  
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ HashFiles('**/yarn.lock') }}

      - name: Run ts-prune
        run: yarn ts-prune --error


unusedexports:
  name: Find unused exports (dead code)
